### ISSUE TITLE
Uploading Files

### ISSUE THREAD

**Issue by goncaloGIT** [Metalnx/metalnx-web#15]
Hello metalnx community

Im having some trouble uploading files, metalnx doesnt give me any error (on the web client), it just says sucess, but the file wasnt uploaded. Through irods cli i have no problem uploading. 
Any suggestions ? 
Is there any log i can see regarding to this problem ?

Best regards

Program   Version
Metatalnx   1.8
iRODS        1.8
Tomcat       1.8
postgresql  9.2.18

**Comment by ajguerra** [comment]
Hello @goncaloGIT ,

We've made some changes on the code to improve performance and feedback for file uploads. 

Unfortunately, this code isn't available yet, but another release will come out any time this week.

Answering your question about where to see the logs, check out the logs from Tomcat and iRODS.

Thx!

**Comment by ajguerra** [comment]
@goncaloGIT check out the new version of Metalnx and let me know if you have still have trouble uploading files.

Thx!

**Comment by goncaloGIT** [comment]
Hello @ajguerra 
I will give you a feedback today or tomorrow

**Comment by ajguerra** [comment]
No problem. Take your time.

**Comment by goncaloGIT** [comment]
Hello @ajguerra 

Im having some trouble installing the new version, but i dont know if the problem is the new version or is the person behind the keyboard ( me ).
I notice that the new versions is compatible with irods 1.10 , so i started from the begining , and installed the 1.10. But i try it in both versions in 1.8 and 1.10 and get the same error:

[ERROR]: Metalnx was not able to contact iRODS server. Check your parameters and try again.

Then im going to see the logs of irods and i get:

![image](https://cloud.githubusercontent.com/assets/25826516/23899518/5776c32a-08ad-11e7-98dd-eb731549bb6b.png)

Its seems like it want's a certificate....... any Ideas ?
Enviroment:
iRODS 1.10
Tomcat 8.5.11
postgresql 9.2.18
java-1.8.0-openjdk-devel

**Comment by ajguerra** [comment]
What does the `core.re` file look file? Is it set to `CS_NEG_REFUSE`?

**Comment by goncaloGIT** [comment]
Brilliant
Change the variable to CS_NEG_REFUSE and worked like a charm.
Also the new version works fine, i can upload files now.
Amazing support, fast and reliable. Keep going with the project.
Thanks

**Comment by ajguerra** [comment]
That's great! Thank you for your feedback!

The reason why you had to change the `core.re` file is because our application by default it is set to `CS_NEG_DONT_CARE` as well as iRODS. 

If both the client and the server are set to `CS_NEG_DONT_CARE`, they will use SSL to exchange messages, which your environment *is not* prepared to. Setting it to `CS_NEG_REFUSE` will tell the server not to use SSL at all. As Metalnx "DONT_CARE", it will do whatever the server tells it to do.

We are going to create a troubleshooting section on our [Wiki](https://github.com/Metalnx/metalnx-web/wiki) and add this installation issue there. Maybe other people will have this same problem later on.

Thx!

**Comment by ngmenyen** [comment]
I also added a troubleshooting page in our wiki about this: https://github.com/Metalnx/metalnx-web/wiki/Troubleshooting
