### ISSUE TITLE
Metalnx 1.3.5 Throws Exception on Copy Operation

### ISSUE THREAD

**Issue by sgworth** [Metalnx/metalnx-web#21]
Steps to reproduce:
- From collections page select a number of files to copy (25)
- Select copy operation and use another collection in the current user's account
- Select copy with metadata
- When you click on "Copy" using "journalctl -f -u tomcat" I can verify the copy operation starts.  However, there is not visual indication on the copy modal that a copy is underway.
- Average user will click "Copy" again to see if something happens.

Clicking copy the second time generates the exception and that in turn breaks the copy operation.  Partial output from journalctl tracing:
l 02 22:37:55 metalnx server[4867]: 2017-07-02 22:37:55 INFO  MetadataServiceImpl:336 - Copying metadata from /tempZone/home/metalnx/lots_of_files/2002_cruise0020 (4).jpg to /tempZone/home/metalnx/test_collection/2002_cruise0020 (4).jpg
Jul 02 22:38:00 metalnx server[4867]: 2017-07-02 22:38:00 INFO  MetadataServiceImpl:336 - Copying metadata from /tempZone/home/metalnx/lots_of_files/2002_cruise0020.jpg to /tempZone/home/metalnx/test_collection/2002_cruise0020.jpg
Jul 02 22:38:04 metalnx server[4867]: 2017-07-02 22:38:04 ERROR TransferOperationsHelper:1326 - exception in transfer
Jul 02 22:38:04 metalnx server[4867]: org.irods.jargon.core.exception.OverwriteException: attempt to overwrite file, target file already exists and no callback listener provided to ask
Jul 02 22:38:04 metalnx server[4867]: at org.irods.jargon.core.pub.DataObjectAOImpl.evaluateOverwrite(DataObjectAOImpl.java:1303)
Jul 02 22:38:04 metalnx server[4867]: at org.irods.jargon.core.pub.DataObjectAOImpl.copyIRODSDataObject(DataObjectAOImpl.java:2697)
Jul 02 22:38:04 metalnx server[4867]: at org.irods.jargon.core.pub.TransferOperationsHelper.processCopyOfSingleFile(TransferOperationsHelper.java:1302)
Jul 02 22:38:04 metalnx server[4867]: at org.irods.jargon.core.pub.DataTransferOperationsImpl.processCopyWhenSourceIsAFile(DataTransferOperationsImpl.java:1725)
Jul 02 22:38:04 metalnx server[4867]: at org.irods.jargon.core.pub.DataTransferOperationsImpl.copy(DataTransferOperationsImpl.java:1673)
Jul 02 22:38:04 metalnx server[4867]: at com.emc.metalnx.services.irods.FileOperationServiceImpl.copy(FileOperationServiceImpl.java:83)
Jul 02 22:38:04 metalnx server[4867]: at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
Jul 02 22:38:04 metalnx server[4867]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jul 02 22:38:04 metalnx server[4867]: at java.lang.reflect.Method.invoke(Method.java:498)
Jul 02 22:38:04 metalnx server[4867]: at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
Jul 02 22:38:04 metalnx server[4867]: at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
Jul 02 22:38:04 metalnx server[4867]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
Jul 02 22:38:04 metalnx server[4867]: at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)

**Comment by ajguerra** [comment]
**When you click on "Copy" using "journalctl -f -u tomcat" I can verify the copy operation starts. However, there is not visual indication on the copy modal that *copy* is underway.**

That's something we need to improve. Right now when you hit "Copy" there's no way for the user to tell whether or not the operation is actually going on (but **it is** in the background). We need to add a spinner or something like that to indicate that the copy operation started.

**Average user will click "Copy" again to see if something happens.**

Did you get an error 500? What do you mean by *average user*? Is *average user* a rodsuser? Did you use a different user to repeat the experiment?

By looking at the logs, I can see that you were trying to overwrite files into the destionation collection - the folder you're trying to copy the files to. It means that the copy function worked in your first try, but you didn't notice that because there was no indicator on the UI. So, when you copied files once again they already existed in the destination collection which threw those exceptions.

**Comment by sgworth** [comment]
No error 500 on the UI, but after the second click if you try going back to the collections or dashboard pages you will get an error message saying that the remaining transfers (the ones which were pending when the exception was thrown) have all failed.  In this case the user was a rodsadmin, but by average user I mean that any person using a UI who clicks on an action button and sees no results will over 99% of the time press the same action button again thinking that their first click did not activate the callback.    No problem with this being an enhancement.   Perhpas a warning in the FAQ about there not being a visual indicator is in order in the meantime.

**Comment by ajguerra** [comment]
Understood and agreed. For now, I added this to the [FAQ](https://github.com/Metalnx/metalnx-web/wiki/FAQ).

Thanks for your feedback @sgworth.
